version: "3.2"
services:
  proxy:
    image: keyle/electron-github-release-proxy:latest
    environment:
      - ACCOUNT=<Put Your GitHub Username Here>
      - REPOSITORY=<Put Your Repo Here>
      - VERSION_PREFIX=<If You App Has A Prefix Put It Here>
      - TOKEN=<PAT>
    ports:
      - 127.0.0.1:5052:3333
    restart: always
