name: Build Backend

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: 🏗️ Build Backend
        run: pnpm build backend --prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: dist/apps/backend
          file: dist/apps/backend/Dockerfile
          push: true
          tags: keyle/electron-github-release-proxy:latest,keyle/electron-github-release-proxy:${{ github.sha }}
